### ISSUE TITLE
Menus broken (again)

### ISSUE THREAD

**Issue by UA-Archiver** [GriefMoDz/user-birthdays#11]
Most menus do not show in Powercord client
Only the settings menu is there in settings (Very obvious) and birthday prompts are shown on birthdays

If possible, please save the birthdays in a file in the plugins folder or somewhere accessible so that even if the plugin breaks, users can access the file and the saved birthdays

**Comment by eternal404** [comment]
Birthdays are already saved!

Here's a guide to help you understand how our settings/birthday manager works.

![image](https://user-images.githubusercontent.com/98427312/155068791-e1b67747-21e2-4346-b3f3-5d1b96218733.png)

Hope this helps! Have an amazing day.
