### ISSUE TITLE
Unable to select specific Days

### ISSUE THREAD

**Issue by SammCheese** [GriefMoDz/user-birthdays#3]
Unsure if its intended but I cant Add Birthdays for days later than 22nd on September.
![image](https://user-images.githubusercontent.com/52699291/134265153-965e54a1-e929-47fc-9a75-be59a9212c16.png)

**Comment by slow** [comment]
You can change the year by using the dropdown at the top of the date picker.

The plugin limits birthdays being set on future dates as someone who would be born in a month for example, wouldn't be using discord.

By changing the year through the dropdown you have the ability to set it on any day and any month.

**Comment by SammCheese** [comment]
Ohhhhh okay that makes sense, i wasnt aware of that. 
Should i close the issue?

**Comment by slow** [comment]
After careful consideration we've decided to revert this change. For situations where you don't know the users birth year, you now have the ability to select any day from the start and the end of the current year.

**Comment by SammCheese** [comment]
Alright, Thank you!

**Comment by slow** [comment]
Just to make this clear, the reverted change I mentioned above is still on the `dev` branch, it will be merged into the main branch after we are done polishing some things. Thank you for your understanding!
