### ISSUE TITLE
How do I assign birthdays? 

### ISSUE THREAD

**Issue by SheepCommander** [GriefMoDz/user-birthdays#8]
Settings still seems to work but I can't figure out where to manage birthdays

![image](https://user-images.githubusercontent.com/66646514/148706290-b4d53187-2f8a-4f80-b463-4a54d5c9c013.png)
![image](https://user-images.githubusercontent.com/66646514/148706294-94cf186a-a86d-4579-bf1b-48cc5fcdc5ba.png)

**Comment by Vukkyy** [comment]
This is caused by #9.

**Comment by SheepCommander** [comment]
Ah I see
